fix: https://github.com/bryanyang0528/ksql-python/issues/98
bryanyang0528/ksql-python pull request #99
Opened 2021-09-02 19:39 UTC by qtfkwk

2021-12-20 14:45 UTC, XHPJ commented
I would actually prefer a 
```
...
else:
       raise InvalidQueryError(rule)
...
```

or am I missing something 🤔  that way you would still raise the exception in case of a missing semicolon

2022-07-04 10:44 UTC, Ga11u commented
> I would actually prefer a
> 
> ```
> ...
> else:
>        raise InvalidQueryError(rule)
> ...
> ```
> 
> or am I missing something 🤔 that way you would still raise the exception in case of a missing semicolon

@XHPJ it should be `if rule[-1:] != "": rise InvalidQueryError(rule)`  This one will cover th case of a missing semicolon and not rise exceptions when there is nothing else to parse.

2022-07-04 10:46 UTC, Ga11u requested changes

2022-07-04 10:46 UTC, Ga11u commented on ksql/upload.py
> -
Instead of removing it. It should be:

```py
            if rule[-1:] != "":
                raise InvalidQueryError(rule)
```

2022-07-23 00:40 UTC, merged